import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home({ user }: any) {
  console.log("🚀 ~ file: index.tsx:9 ~ Home ~ user:", user)

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          {user?.name ? "Hello " + user.name : "Hello World"}
        </div>
      </main>
    </>
  )
}

export async function getServerSideProps() {
  const getUser = await fetch('http://localhost:3000/api/user').then(res => res.json()).catch(err => err)
  console.log("🚀 ~ file: index.tsx:31 ~ getServerSideProps ~ res:", getUser)
  return {
    props: {
      inter,
      user: getUser,
    },
  }
}